// <auto-generated />
using System;
using LibararyData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibararyData.Migrations
{
    [DbContext(typeof(LibararyContext))]
    partial class LibararyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibararyData.Models.BranchHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId");

                    b.Property<string>("CloseTime");

                    b.Property<string>("DayOfWeek");

                    b.Property<string>("OpenTime");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchHours");
                });

            modelBuilder.Entity("LibararyData.Models.CheckOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Since");

                    b.Property<DateTime>("Until");

                    b.Property<int>("libararyAssetsId");

                    b.Property<int?>("libararyCardId");

                    b.HasKey("Id");

                    b.HasIndex("libararyAssetsId");

                    b.HasIndex("libararyCardId");

                    b.ToTable("CheckOuts");
                });

            modelBuilder.Entity("LibararyData.Models.CheckOutHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckedIn");

                    b.Property<DateTime>("CheckedOut");

                    b.Property<int>("libararyAssetsId");

                    b.Property<int>("libararyCardId");

                    b.HasKey("Id");

                    b.HasIndex("libararyAssetsId");

                    b.HasIndex("libararyCardId");

                    b.ToTable("GetCheckOutHistories");
                });

            modelBuilder.Entity("LibararyData.Models.Hold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HoldPlaced");

                    b.Property<int?>("LibararyAssetsId");

                    b.Property<int?>("LibararyCardId");

                    b.HasKey("Id");

                    b.HasIndex("LibararyAssetsId");

                    b.HasIndex("LibararyCardId");

                    b.ToTable("Holds");
                });

            modelBuilder.Entity("LibararyData.Models.LibararyAssets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<int?>("LocationId");

                    b.Property<int>("NumberOfCopies");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("libararyAssets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LibararyAssets");
                });

            modelBuilder.Entity("LibararyData.Models.LibararyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime>("OpenDate");

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("LibararyBranches");
                });

            modelBuilder.Entity("LibararyData.Models.LibararyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<decimal>("Fees");

                    b.HasKey("Id");

                    b.ToTable("LibararyCards");
                });

            modelBuilder.Entity("LibararyData.Models.Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<int?>("HomeLibararyBranchId");

                    b.Property<string>("LastName");

                    b.Property<string>("TelephoneNumber");

                    b.Property<int?>("libararyCardId");

                    b.HasKey("Id");

                    b.HasIndex("HomeLibararyBranchId");

                    b.HasIndex("libararyCardId");

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("LibararyData.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("LibararyData.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("LibararyData.Models.Book", b =>
                {
                    b.HasBaseType("LibararyData.Models.LibararyAssets");

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("DeweyUndex")
                        .IsRequired();

                    b.Property<string>("ISBN")
                        .IsRequired();

                    b.ToTable("Book");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("LibararyData.Models.BranchHours", b =>
                {
                    b.HasOne("LibararyData.Models.LibararyBranch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");
                });

            modelBuilder.Entity("LibararyData.Models.CheckOut", b =>
                {
                    b.HasOne("LibararyData.Models.LibararyAssets", "libararyAssets")
                        .WithMany()
                        .HasForeignKey("libararyAssetsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibararyData.Models.LibararyCard", "libararyCard")
                        .WithMany("CheckOuts")
                        .HasForeignKey("libararyCardId");
                });

            modelBuilder.Entity("LibararyData.Models.CheckOutHistory", b =>
                {
                    b.HasOne("LibararyData.Models.LibararyAssets", "libararyAssets")
                        .WithMany()
                        .HasForeignKey("libararyAssetsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibararyData.Models.LibararyCard", "libararyCard")
                        .WithMany()
                        .HasForeignKey("libararyCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LibararyData.Models.Hold", b =>
                {
                    b.HasOne("LibararyData.Models.LibararyAssets", "LibararyAssets")
                        .WithMany()
                        .HasForeignKey("LibararyAssetsId");

                    b.HasOne("LibararyData.Models.LibararyCard", "LibararyCard")
                        .WithMany()
                        .HasForeignKey("LibararyCardId");
                });

            modelBuilder.Entity("LibararyData.Models.LibararyAssets", b =>
                {
                    b.HasOne("LibararyData.Models.LibararyBranch", "Location")
                        .WithMany("LibararyAssets")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("LibararyData.Models.Patron", b =>
                {
                    b.HasOne("LibararyData.Models.LibararyBranch", "HomeLibararyBranch")
                        .WithMany("Patrons")
                        .HasForeignKey("HomeLibararyBranchId");

                    b.HasOne("LibararyData.Models.LibararyCard", "libararyCard")
                        .WithMany()
                        .HasForeignKey("libararyCardId");
                });
#pragma warning restore 612, 618
        }
    }
}
